// Generated by scripts/generate-edge-shared.mjs. Do not edit manually.

import { isRegularSeasonGameId } from './gameId.ts'

export type ScheduleSourceGame = {
    gameId: string
    gameDate: string
    homeTeam: string
    awayTeam: string
    status: string
    startedAt: string | null
    weekNumber: number | null
    scheduleSeasonYear?: string | null
}

export type ScheduleGameRow = {
    nba_game_id: string
    season_year: number
    game_date: string
    home_team: string
    away_team: string
    status: string
    started_at: string | null
    game_time: string | null
    ended_at: null
    week_number: number
    updated_at: string
}

export type SeasonWeekRow = {
    season_year: number
    week_number: number
    week_start: string
    week_end: string
}

export type ScheduleSyncPlan = {
    regularSeason: ScheduleSourceGame[]
    seasonStart: string | null
    seasonYear: number | null
    rows: ScheduleGameRow[]
    weeks: SeasonWeekRow[]
    offseasonStale?: boolean
}

export function seasonYearForGameDate(gameDate: string): number {
    const [yearText, monthText] = gameDate.split('-')
    const year = Number(yearText)
    const month = Number(monthText)
    if (!Number.isInteger(year) || !Number.isInteger(month)) {
        throw new Error(`Could not derive season year from game date: ${gameDate}`)
    }
    return month >= 10 ? year + 1 : year
}

export function normalizedScheduleTimestamp(value: string | null): string | null {
    if (!value) return null
    const date = new Date(value)
    if (Number.isNaN(date.getTime())) return null
    return date.toISOString()
}

export function etDateKey(now = new Date()): string {
    const parts = new Intl.DateTimeFormat('en-US', {
        timeZone: 'America/New_York',
        year: 'numeric',
        month: '2-digit',
        day: '2-digit',
    }).formatToParts(now)
    const values = Object.fromEntries(parts.map((part) => [part.type, part.value]))
    return `${values.year}-${values.month}-${values.day}`
}

export function seasonEndYearFromScheduleLabel(label: string | null | undefined): number | null {
    const match = label?.match(/^(\d{4})-(\d{2}|\d{4})$/)
    if (!match) return null
    const startYear = Number(match[1])
    const endText = match[2]
    if (endText.length === 4) return Number(endText)
    const century = Math.floor(startYear / 100) * 100
    const sameCenturyEnd = century + Number(endText)
    return sameCenturyEnd <= startYear ? sameCenturyEnd + 100 : sameCenturyEnd
}

// From the last regular-season game (mid-April) until the new schedule is
// published (~Sept 1), the NBA CDN serves last season's schedule. That is the
// normal offseason state, not a failure: report it as a skip so the daily
// sync stays quiet instead of erroring every day from May to August.
export function assertScheduleFresh(
    regularSeason: { gameDate: string; scheduleSeasonYear?: string | null }[],
    seasonYear: number,
    now = new Date(),
): 'fresh' | 'offseason-stale' {
    const sourceSeasonYear = seasonEndYearFromScheduleLabel(regularSeason[0]?.scheduleSeasonYear)
    if (sourceSeasonYear != null && sourceSeasonYear !== seasonYear) {
        throw new Error(`NBA schedule season label ${regularSeason[0]?.scheduleSeasonYear} does not match game dates for season ${seasonYear}`)
    }

    const dates = regularSeason.map((game) => game.gameDate).sort()
    const latestGameDate = dates[dates.length - 1]
    const today = etDateKey(now)
    if (latestGameDate && latestGameDate < today) {
        const month = Number(today.slice(5, 7))
        if (month >= 4 && month <= 8) return 'offseason-stale'
        throw new Error(`NBA schedule payload is stale; latest regular-season game ${latestGameDate} is before ${today}`)
    }
    return 'fresh'
}

export function buildSeasonWeekRows(
    games: { game_date: string; week_number: number }[],
    seasonYear: number,
): SeasonWeekRow[] {
    const weekMap: Record<number, { start: string; end: string }> = {}
    for (const game of games) {
        if (!game.week_number) continue
        const existing = weekMap[game.week_number]
        if (!existing) {
            weekMap[game.week_number] = { start: game.game_date, end: game.game_date }
            continue
        }
        if (game.game_date < existing.start) existing.start = game.game_date
        if (game.game_date > existing.end) existing.end = game.game_date
    }

    return Object.entries(weekMap).map(([weekNumber, range]) => ({
        season_year: seasonYear,
        week_number: parseInt(weekNumber),
        week_start: range.start,
        week_end: range.end,
    }))
}

export function buildScheduleSyncPlan(raw: ScheduleSourceGame[], now = new Date()): ScheduleSyncPlan {
    const regularSeason = raw.filter((game) => isRegularSeasonGameId(game.gameId))
    const dateCounts = new Map<string, number>()
    for (const game of regularSeason) {
        dateCounts.set(game.gameDate, (dateCounts.get(game.gameDate) ?? 0) + 1)
    }

    const bulkStartDates = [...dateCounts.entries()]
        .filter(([, count]) => count >= 5)
        .map(([date]) => date)
        .sort()
    const seasonStart = bulkStartDates[0] ?? regularSeason.map((game) => game.gameDate).sort()[0] ?? null
    if (!seasonStart) {
        return { regularSeason, seasonStart: null, seasonYear: null, rows: [], weeks: [] }
    }

    const seasonYear = seasonYearForGameDate(seasonStart)
    if (assertScheduleFresh(regularSeason, seasonYear, now) === 'offseason-stale') {
        return { regularSeason, seasonStart, seasonYear, rows: [], weeks: [], offseasonStale: true }
    }
    const updatedAt = now.toISOString()
    const rows = regularSeason
        .filter((game) => game.homeTeam && game.awayTeam)
        .map((game) => ({
            nba_game_id: game.gameId,
            season_year: seasonYear,
            game_date: game.gameDate,
            home_team: game.homeTeam,
            away_team: game.awayTeam,
            status: game.status,
            started_at: normalizedScheduleTimestamp(game.startedAt),
            game_time: normalizedScheduleTimestamp(game.startedAt),
            ended_at: null,
            week_number: game.weekNumber ?? 0,
            updated_at: updatedAt,
        }))

    return {
        regularSeason,
        seasonStart,
        seasonYear,
        rows,
        weeks: buildSeasonWeekRows(rows, seasonYear),
    }
}
