// Generated by scripts/generate-edge-shared.mjs. Do not edit manually.

function zonedParts(date: Date, timeZone: string): { year: number; month: number } {
    const parts = new Intl.DateTimeFormat('en-US', {
        timeZone,
        year: 'numeric',
        month: 'numeric',
    }).formatToParts(date)

    const year = Number(parts.find((part) => part.type === 'year')?.value)
    const month = Number(parts.find((part) => part.type === 'month')?.value)
    if (!Number.isInteger(year) || !Number.isInteger(month)) {
        throw new Error(`Could not resolve season year in ${timeZone}`)
    }

    return { year, month }
}

export function currentSeasonYear(
    now = new Date(),
    timeZone = 'America/New_York',
): number {
    const { year, month } = zonedParts(now, timeZone)
    return month >= 10 ? year + 1 : year
}
