import { readFileSync } from 'node:fs'
import path from 'node:path'
import { describe, expect, it } from 'vitest'

describe('dynasty engine runtime parity', () => {
    it('keeps the generated Edge engine equal to the canonical core source', () => {
        const root = path.resolve(import.meta.dirname, '..')
        const canonical = readFileSync(path.join(root, 'core/src/dynasty/decisionEngine.ts'), 'utf8')
        const generated = readFileSync(path.join(root, 'supabase/functions/_shared/dynastyDecisionEngine.ts'), 'utf8')
            .replace('// Generated by scripts/generate-edge-shared.mjs. Do not edit manually.\n\n', '')
            .replace("import { calculateFantasyPoints } from './scoringCore.ts'", "import { calculateFantasyPoints } from '../scoring/formula'")
            .replace("import type { ScoringSettings, StatLine } from './scoringCore.ts'", "import type { ScoringSettings, StatLine } from '../scoring/types'")

        expect(generated).toBe(canonical)
    })
})
