import { describe, expect, it } from 'vitest'
import {
    functionPrivilegeStatements,
    latestCronScheduleStatement,
    latestFunctionDefinition,
    latestPolicyDefinition,
    read,
    tablePrivilegeStatements,
} from './source-guard'

const migration = read('supabase/migrations/20260701000002_fantasypros_projection_source.sql')
const syncProjectionSource = read('supabase/functions/sync-projections/index.ts')
const parserSource = read('supabase/functions/sync-projections/parser.ts')
const matchSource = read('supabase/functions/sync-projections/match.ts')
const lineupOptimizerSource = read('supabase/functions/lineup-optimizer/index.ts')
const autoSetSource = read('lib/lineup/autoSet.ts')
const playerItem = read('components/PlayerSearchItem.tsx')
const playerDetail = read('app/player/[id].tsx')
const databaseTypes = read('types/database.ts')
const packageJson = read('package.json')
const dbProjectionTest = read('tests/db/fantasypros-projections.sql')

describe('FantasyPros projection source implementation', () => {
    it('stores auditable source runs and raw rows, including unmatched rows', () => {
        expect(migration).toContain('CREATE TABLE IF NOT EXISTS public.projection_sync_runs')
        expect(migration).toContain('CREATE TABLE IF NOT EXISTS public.fantasypros_projection_rows')
        expect(migration).toContain("match_status text NOT NULL CHECK (match_status IN ('matched', 'unmatched', 'ambiguous'))")
        expect(migration).toContain('UNIQUE (run_id, source_row_number)')
        expect(migration).toContain("source_url !~ '/(api|json|xml|ajax)/'")
        expect(migration).toContain('idx_fantasypros_projection_rows_daily_read')
        expect(migration).toContain('idx_fantasypros_projection_rows_weekly_read')
        expect(migration).toContain('idx_fantasypros_projection_rows_unmatched')
        expect(databaseTypes).toContain('fantasypros_projection_rows: {')
        expect(databaseTypes).toContain('projection_sync_runs: {')

        expect(matchSource).toContain("status: 'matched' | 'unmatched' | 'ambiguous'")
        expect(matchSource).toContain("reason: 'no normalized-name match'")
        expect(matchSource).toContain("Database['public']['Tables']['fantasypros_projection_rows']['Insert']")
    })

    it('locks projection write tables behind RLS and service-role mutation grants', () => {
        const runPolicy = latestPolicyDefinition('projection_sync_runs_select_authenticated', 'projection_sync_runs')
        const rowPolicy = latestPolicyDefinition('fantasypros_projection_rows_select_authenticated', 'fantasypros_projection_rows')
        const runPrivileges = tablePrivilegeStatements('projection_sync_runs').join('\n')
        const rowPrivileges = tablePrivilegeStatements('fantasypros_projection_rows').join('\n')

        expect(runPolicy).toContain('FOR SELECT TO authenticated USING (true)')
        expect(rowPolicy).toContain('FOR SELECT TO authenticated USING (true)')
        expect(runPrivileges).toContain('REVOKE ALL ON public.projection_sync_runs FROM anon, authenticated')
        expect(rowPrivileges).toContain('REVOKE ALL ON public.fantasypros_projection_rows FROM anon, authenticated')
        expect(runPrivileges).toContain('GRANT SELECT, INSERT, UPDATE, DELETE ON public.projection_sync_runs TO service_role')
        expect(rowPrivileges).toContain('GRANT SELECT, INSERT, UPDATE, DELETE ON public.fantasypros_projection_rows TO service_role')
    })

    it('uses public FantasyPros HTML only and enforces the crawl delay between source pages', () => {
        expect(syncProjectionSource).toContain('https://www.fantasypros.com/nba/projections/daily-overall.php')
        expect(syncProjectionSource).toContain('https://www.fantasypros.com/nba/projections/avg-weekly-overall.php')
        expect(syncProjectionSource).toContain('https://www.fantasypros.com/nba/projections/weekly-overall.php')
        expect(syncProjectionSource).not.toMatch(/fantasypros\.com\/(?:api|json|xml|ajax)\//)
        expect(syncProjectionSource).toContain('const FANTASYPROS_DELAY_MS = 5000')
        expect(syncProjectionSource).toContain('if (i > 0) await sleep(FANTASYPROS_DELAY_MS)')
        expect(syncProjectionSource).toContain("'Accept': 'text/html,application/xhtml+xml'")
        expect(parserSource).toContain('findProjectionTable')
    })

    it('keeps sync writes on generated Supabase database types', () => {
        expect(syncProjectionSource).toContain("type ProjectionSyncRunInsert = Database['public']['Tables']['projection_sync_runs']['Insert']")
        expect(syncProjectionSource).toContain("type ProjectionSyncRunUpdate = Database['public']['Tables']['projection_sync_runs']['Update']")
        expect(syncProjectionSource).toContain("type InternalProjectionUpsert = Database['public']['Tables']['player_projections']['Insert']")
        expect(syncProjectionSource).not.toContain('type UntypedSupabase')
        expect(syncProjectionSource).not.toContain('as unknown as UntypedSupabase')
        expect(syncProjectionSource).not.toContain('const db = supabase')
    })

    it('schedules backend cron refreshes and keeps the wrapper service-role only', () => {
        const cron = latestCronScheduleStatement('nba-sync-projections')
        const wrapper = latestFunctionDefinition('invoke_projection_sync_if_due')
        const privileges = functionPrivilegeStatements('invoke_projection_sync_if_due').join('\n')

        expect(cron).toContain("'0 12-23 * * *'")
        expect(cron).toContain('public.invoke_projection_sync_if_due()')
        expect(wrapper).toContain('EXTRACT(HOUR FROM v_now_et)::int = 8')
        expect(wrapper).toContain('now() < v_first_lock')
        expect(wrapper).toContain("public.invoke_edge_function('sync-projections')")
        expect(privileges).toContain('REVOKE ALL ON FUNCTION public.invoke_projection_sync_if_due() FROM PUBLIC')
        expect(privileges).toContain('REVOKE ALL ON FUNCTION public.invoke_projection_sync_if_due() FROM authenticated')
        expect(privileges).toContain('GRANT EXECUTE ON FUNCTION public.invoke_projection_sync_if_due() TO service_role')
    })

    it('exposes league-scored projection priority and fallback behavior through one RPC', () => {
        const projectionRpc = latestFunctionDefinition('get_league_projection_rows')
        const scoringRpc = latestFunctionDefinition('projection_stat_fantasy_points')

        expect(scoringRpc).toContain("p_scoring_settings->>'points'")
        expect(scoringRpc).toContain("p_scoring_settings->>'three_pointers_made'")
        expect(scoringRpc).toContain("p_scoring_settings->>'field_goals_made'")
        expect(scoringRpc).toContain("p_scoring_settings->>'field_goals_attempted'")
        expect(scoringRpc).toContain("p_scoring_settings->>'free_throws_made'")
        expect(scoringRpc).toContain("p_scoring_settings->>'free_throws_attempted'")
        expect(scoringRpc).toContain("p_scoring_settings->>'double_double'")
        expect(scoringRpc).toContain("p_scoring_settings->>'triple_double'")
        expect(scoringRpc).toContain('ten_plus_categories >= 2')
        expect(scoringRpc).toContain('ten_plus_categories >= 3')
        expect(projectionRpc).toContain("r.projection_type = 'daily'")
        expect(projectionRpc).toContain("r.fetched_at >= now() - interval '36 hours'")
        expect(projectionRpc).toContain("r.projection_type = 'weekly_avg'")
        expect(projectionRpc).toContain("r.projection_type = 'weekly_total'")
        expect(projectionRpc).toContain('latest_daily_run AS')
        expect(projectionRpc).toContain('latest_weekly_avg_run AS')
        expect(projectionRpc).toContain('latest_weekly_total_run AS')
        expect(projectionRpc).toContain("latest_run.status IN ('success', 'failed', 'skipped')")
        expect(projectionRpc.match(/JOIN public\.projection_sync_runs psr/g)?.length).toBe(3)
        expect(projectionRpc.match(/JOIN base_players projected_player/g)?.length).toBe(5)
        expect(projectionRpc).toContain('ON projected_player.id = r.player_id')
        expect(projectionRpc).toContain('ON projected_player.id = pp.player_id')
        expect(projectionRpc).toContain('ON projected_player.id = avg.player_id')
        expect(projectionRpc).toContain("psr.status = 'success'")
        expect(projectionRpc).toContain('psr.completed_at IS NOT NULL')
        expect(projectionRpc).toContain('uses_fantasypros_unsupported_scoring')
        expect(projectionRpc).not.toContain("scoring_settings->>'double_double')::numeric, 0) <> 0")
        expect(projectionRpc).not.toContain("scoring_settings->>'triple_double')::numeric, 0) <> 0")
        expect(projectionRpc.match(/AND NOT l\.uses_fantasypros_unsupported_scoring/g)?.length).toBe(3)
        expect(projectionRpc).not.toContain('uses_fantasypros_unsupported_scoring THEN 5')
        expect(projectionRpc).toContain('public.player_projections pp')
        expect(projectionRpc).toContain('pp.projected_stat_points')
        expect(projectionRpc).toContain('pp.projected_field_goals_made')
        expect(projectionRpc).toContain('pp.projected_double_doubles')
        expect(projectionRpc).not.toContain('pp.projected_points AS projection_fantasy_points')
        expect(projectionRpc).toContain('public.mv_player_season_averages avg')
        expect(projectionRpc).toContain('avg.avg_field_goals_made')
        expect(projectionRpc).toContain('avg.avg_free_throws_attempted')
        expect(projectionRpc).toContain("WHEN args.view_name = 'week_avg' THEN 1")
        expect(projectionRpc).toContain('ELSE 2')
        expect(projectionRpc).toContain('fantasypros_weekly_avg_total')
        expect(projectionRpc).toContain('FantasyPros Week Avg x GP')
        expect(projectionRpc).toContain('ORDER BY cu.player_id, cu.priority ASC')
        expect(syncProjectionSource).toContain('projected_field_goals_made')
        expect(syncProjectionSource).toContain('projected_double_doubles')
        expect(projectionRpc).toContain('week_game_counts AS')
        expect(projectionRpc).toContain('m.games_multiplier')
        expect(projectionRpc).toContain('COALESCE(wgc.scheduled_games, 0)::numeric')
        expect(projectionRpc).toContain('COALESCE(r.points, 0) / NULLIF(r.games_played, 0)')
        expect(projectionRpc).toContain('THEN r.games_played::numeric')
        expect(projectionRpc).toContain("WHEN args.view_name = 'week_total' THEN 0::numeric")
        expect(projectionRpc).toContain("WHEN args.view_name = 'week_total' THEN COALESCE(pp.projected_double_doubles, 0) * m.games_multiplier")
        expect(projectionRpc).toContain("WHEN args.view_name = 'week_total' THEN COALESCE(pp.projected_triple_doubles, 0) * m.games_multiplier")
        expect(syncProjectionSource).toMatch(
            /\.from\('player_game_stats'\)[\s\S]*\.order\('player_id', \{ ascending: true \}\)[\s\S]*\.order\('game_id', \{ ascending: true \}\)[\s\S]*\.range\(from, from \+ PAGE - 1\)/,
        )
    })

    it('enriches player search projections after applying player filters', () => {
        const searchRpc = latestFunctionDefinition('search_players')

        expect(searchRpc).toContain('filtered_base AS')
        expect(searchRpc).toContain('paged_base AS')
        expect(searchRpc).toContain('COALESCE((SELECT array_agg(paged_base.id ORDER BY paged_base.id) FROM paged_base), ARRAY[]::uuid[])')
        expect(searchRpc).toContain('pb.avg_fantasy_points,')
        expect(searchRpc).toContain('proj.projection_fantasy_points,')
        expect(searchRpc).toContain('proj.projection_view,')
        expect(searchRpc).toContain('FROM paged_base pb')
        expect(searchRpc).toContain('ORDER BY pb.page_rank')
        expect(searchRpc).not.toContain('COALESCE(proj.projection_fantasy_points, fb.avg_fantasy_points) AS avg_fantasy_points')
        expect(searchRpc).not.toContain("'today',\n    NULL,\n    1000")
    })

    it('has executable DB coverage for projection source priority and player search field separation', () => {
        expect(packageJson).toContain('"test:db:fantasypros-projections"')
        expect(dbProjectionTest).toContain('public.get_league_projection_rows')
        expect(dbProjectionTest).toContain('public.search_players')
        expect(dbProjectionTest).toContain("v_row.projection_source <> 'fantasypros_daily'")
        expect(dbProjectionTest).toContain("v_row.projection_source <> 'internal'")
        expect(dbProjectionTest).toContain("v_row.projection_source <> 'season_avg'")
        expect(dbProjectionTest).toContain('v_first.id <>')
        expect(dbProjectionTest).toContain('v_first.projection_fantasy_points <> 20')
        expect(dbProjectionTest).toContain('v_projection_leader.avg_fantasy_points <> 10')
        expect(dbProjectionTest).toContain('v_projection_leader.projection_fantasy_points <> 124.5')
        expect(dbProjectionTest).toContain("v_projection_leader.projection_view <> 'today'")
        expect(dbProjectionTest).toContain('Week-total view should scale FantasyPros weekly-average fallback rows by GP')
        expect(dbProjectionTest).toContain('Unsupported weekly total fallback should scale internal projections')
        expect(dbProjectionTest).toContain('Unsupported weekly total fallback should scale season averages')
    })

    it('does not record zero-row FantasyPros parses as successful sync runs', () => {
        expect(syncProjectionSource).toContain('if (parsedRows.length === 0)')
        expect(syncProjectionSource).toContain("status: 'skipped'")
        expect(syncProjectionSource).toContain('No FantasyPros ${projectionType} projection rows parsed from public HTML')
        expect(syncProjectionSource).toContain('class ProjectionFetchError extends Error')
        expect(syncProjectionSource).toContain('error instanceof ProjectionFetchError ? error.httpStatus : undefined')
    })

    it('wires player, Auto-Set, and season optimizer surfaces to the shared projection source', () => {
        expect(playerItem).toContain('projection_fantasy_points')
        expect(playerDetail).toContain('NextProjectionCard')

        expect(autoSetSource).toContain('getProjectionMap')
        expect(autoSetSource).toContain('projection_fantasy_points')
        expect(autoSetSource).toContain('projectionView')
        expect(lineupOptimizerSource).toContain("supabase.rpc('get_league_projection_rows'")
        expect(lineupOptimizerSource).toContain('projection_fantasy_points')
        expect(lineupOptimizerSource).toContain('projection_view')
        expect(lineupOptimizerSource).toContain('auto-set projection sources')
        expect(autoSetSource).toContain('startedTeams.has(player.nbaTeam)')
        expect(lineupOptimizerSource).toContain('startedTeams.has(player.nbaTeam)')
        expect(lineupOptimizerSource).toContain('if (team && startedTeams.has(team)) {')
        expect(lineupOptimizerSource).toContain('lockedPlayerIds.add(entry.player_id)')
        expect(lineupOptimizerSource).toContain("const isStarter = entry.slot_type !== 'BE' && entry.slot_type !== 'IR'")
    })
})
