import { describe, expect, it } from 'vitest'
import { latestFunctionDefinition, read } from './source-guard'

const goalMigration = read('supabase/migrations/20260701000001_mock_draft_rooms_lineup_optimizer.sql')
const leagueScreen = read('app/(tabs)/league.tsx')
const leagueScreenState = read('hooks/use-league-screen-state.ts')
const draftChips = read('components/league/DraftChips.tsx')
const draftActiveState = read('components/league/DraftActiveState.tsx')
const draftSetupPanels = read('components/league/DraftSetupPanels.tsx')
const mockRoomsPanel = read('components/league/MockRoomsPanel.tsx')
const settingsPanel = read('components/league/SettingsPanel.tsx')
const leagueStandings = read('components/league/LeagueStandings.tsx')
const leagueStandingsIntro = read('components/league/LeagueStandingsIntro.tsx')
const leagueActivityFeed = read('components/league/LeagueActivityFeed.tsx')
const leaguePicksBank = read('components/league/LeaguePicksBank.tsx')
const leagueTabBar = read('components/league/LeagueTabBar.tsx')
const webViewportHook = read('hooks/use-web-viewport.ts')
const segmentedControl = read('components/ui/SegmentedControl.tsx')
const feedbackUi = read('components/ui/feedback.tsx')
const leagueTabs = read('lib/league/tabs.ts')
const draftLib = read('lib/draft.ts')
const mockRoomsLib = read('lib/mockDraftRooms.ts')
const lineupOptimizer = read('supabase/functions/lineup-optimizer/index.ts')
const draftApi = read('supabase/functions/api/draft.ts')

describe('fantasy draft and auction experience goals', () => {
    it('shows auction player age from dynasty ranking data', () => {
        expect(draftLib).toContain('age: number | null')
        expect(draftLib).toContain('getLatestDynastyAges')
        expect(draftLib).toContain(".from('dynasty_rankings')")
        expect(read('app/(modals)/draft-room.tsx')).toContain('ageLabel')
    })

    it('models joinable scheduled mock draft rooms scoped to joined members', () => {
        expect(goalMigration).toContain('CREATE TABLE IF NOT EXISTS public.draft_room_members')
        expect(goalMigration).toContain('created_by_member_id')
        expect(goalMigration).toContain('scheduled_at')
        expect(latestFunctionDefinition('create_mock_draft_room_atomic')).toContain('INSERT INTO public.drafts')
        expect(latestFunctionDefinition('create_mock_draft_room_atomic')).toContain("'pending'")
        expect(latestFunctionDefinition('join_mock_draft_room_atomic')).toContain("v_draft.status <> 'pending'")
        expect(latestFunctionDefinition('start_mock_draft_room_atomic')).toContain('FROM public.draft_room_members')
        expect(latestFunctionDefinition('start_mock_draft_room_atomic')).toContain('Need at least 2 joined managers')
        expect(draftApi).toContain('Mock drafts must be created and started from a mock draft room')
        expect(mockRoomsLib).toContain("roomStatus: MockDraftRoomStatus")
        expect(mockRoomsLib).toContain("'scheduled'")
        expect(mockRoomsLib).toContain("'live'")
        expect(mockRoomsLib).toContain("'completed'")
        expect(mockRoomsPanel).toContain('function roomStartBlockedCopy')
        expect(mockRoomsPanel).toContain("`Needs ${missing} ${missing === 1 ? 'Team' : 'Teams'}`")
        expect(mockRoomsPanel).toContain('Start ${roomName} unavailable.')
        expect(mockRoomsPanel).toContain('Needs ${missing} more joined')
    })

    it('keeps draft navigation focused by tab purpose', () => {
        for (const label of ['Results', 'Auctions', 'Mock Rooms', 'Draft Board', 'Settings', 'History']) {
            expect(leagueTabs).toContain(label)
        }
        expect(leagueScreen).toContain('<MockRoomsPanel')
        expect(leagueScreen).toContain('<AuctionPanel')
        expect(leagueScreen).toContain('<DraftBoardPanel')
        expect(draftActiveState).toContain('function ActiveDraftEntry')
        expect(draftSetupPanels).toContain('filterType="snake"')
        expect(draftActiveState).toContain('if (compactActiveDraft) {')
        expect(draftActiveState).toContain('styles.activeDraftCardCompact')
        expect(draftActiveState).toContain('styles.activeDraftCompactTitle')
        expect(draftActiveState).toContain('compactActiveDraft && styles.activeDraftCompactButton')
        expect(draftSetupPanels).toContain('compactSetup && (hasActiveAuction || canStartAuction) && styles.activeDraftPanelScrollCompact')
        expect(draftSetupPanels).toContain('activeDraftPanelScrollCompact: { paddingTop: spacing.xs }')
        expect(draftActiveState).toContain('paddingVertical: spacing.xxs')
        expect(draftSetupPanels).toContain('auctionPanelCardCompact: {')
        expect(draftSetupPanels).toContain('paddingTop: 0')
        expect(draftSetupPanels).toContain('paddingBottom: spacing.xs')
        expect(mockRoomsPanel).not.toContain('Start Mock Auction')
        expect(mockRoomsPanel).not.toContain('Start Mock Rookie Draft')
        expect(draftSetupPanels).not.toContain('Start Mock Auction')
        expect(draftSetupPanels).not.toContain('Start Mock Rookie Draft')
    })

    it('keeps draft setup chip groups oriented as horizontal radiogroups', () => {
        const chipGroup = draftChips.slice(
            draftChips.indexOf('function DraftChips'),
            draftChips.indexOf('const draftTimerChipLabel'),
        )
        expect(chipGroup).toContain('role="radiogroup"')
        expect(chipGroup).toContain('aria-label={groupLabel}')
        expect(chipGroup).toContain('aria-orientation="horizontal"')
        expect(chipGroup).toContain('accessibilityRole="radiogroup"')
        expect(chipGroup).toContain('role="radio"')
        expect(chipGroup).toContain('aria-checked={selected}')
        expect(draftChips).toContain('function nextChipIndex')
        expect(draftChips).toContain("if (key === 'ArrowRight' || key === 'ArrowDown') return (currentIndex + 1) % count")
        expect(draftChips).toContain('function focusDraftChip')
        expect(draftChips).toContain("'dialog'")
        expect(draftChips).toContain("'alertdialog'")
        expect(chipGroup).toContain('nativeID={draftChipId(idBase, option.value)}')
        expect(chipGroup).toContain('tabIndex={selected ? 0 : -1}')
        expect(chipGroup).toContain('onKeyDown: (event) => handleKeyDown(event, index)')
        expect(draftSetupPanels).toContain('function auctionStartButtonLabel')
        expect(draftSetupPanels).toContain('Start auction draft, ${draftTimerSeconds} second timer, ${NOMINATION_ORDER_MODE_LABELS[nominationMode]} nomination order')
        expect(draftSetupPanels).toContain('const startAuctionAccessibilityLabel = auctionStartButtonLabel(draftTimerSeconds, nominationMode)')
        expect(draftSetupPanels).toContain('aria-label={startAuctionAccessibilityLabel}')
        expect(draftSetupPanels).toContain('function rookieStartButtonLabel')
        expect(draftSetupPanels).toContain('Start rookie draft, ${rookieRounds} rounds, ${draftTimerSeconds} second timer, ${ROOKIE_TIMER_EXPIRY_BEHAVIOR_LABELS[rookieTimerExpiryBehavior]} timeout behavior')
        expect(draftSetupPanels).toContain('const startRookieAccessibilityLabel = rookieStartButtonLabel(rookieRounds, draftTimerSeconds, rookieTimerExpiryBehavior)')
        expect(draftSetupPanels).toContain('aria-label={startRookieAccessibilityLabel}')
    })

    it('keeps irreversible draft-start confirmations configuration-aware', () => {
        expect(leagueScreenState).toContain('function auctionDraftConfirmationMessage')
        expect(leagueScreenState).toContain('with a ${draftTimerSeconds}-second timer and ${NOMINATION_ORDER_MODE_LABELS[nominationMode].toLowerCase()} nomination order')
        expect(leagueScreenState).toContain('confirmAction(')
        expect(leagueScreenState).toContain('auctionDraftConfirmationMessage(draftTimerSeconds, nominationMode)')
        expect(leagueScreenState).toContain("'Start Auction'")
        expect(leagueScreenState).toContain('function rookieDraftConfirmationMessage')
        expect(leagueScreenState).toContain('for ${rookieRounds} rounds with a ${draftTimerSeconds}-second timer and ${ROOKIE_TIMER_EXPIRY_BEHAVIOR_LABELS[rookieTimerExpiryBehavior].toLowerCase()} timeout behavior')
        expect(leagueScreenState).toContain('rookieDraftConfirmationMessage(rookieRounds, draftTimerSeconds, rookieTimerExpiryBehavior)')
        expect(leagueScreenState).toContain("'Start Rookie'")
        expect(leagueScreenState).not.toContain('This will begin the auction draft for all teams. This cannot be undone.')
        expect(leagueScreenState).not.toContain('This will begin the rookie snake draft. This cannot be undone.')
    })

    it('keeps in-app confirmations exposed as labelled modal dialogs', () => {
        expect(feedbackUi).toContain('const dialogContainerId = `${dialogId}-confirm-dialog`')
        expect(feedbackUi).toContain('const dialogTitleId = `${dialogId}-confirm-title`')
        expect(feedbackUi).toContain('const dialogMessageId = `${dialogId}-confirm-message`')
        expect(feedbackUi).toContain('const DIALOG_FOCUS_DELAYS')
        expect(feedbackUi).toContain('const DIALOG_FOCUSABLE_SELECTOR')
        expect(feedbackUi).toContain('function trapDialogTabFocus')
        expect(feedbackUi).toContain("if (event.key !== 'Tab'")
        expect(feedbackUi).toContain('event.preventDefault?.()')
        expect(feedbackUi).toContain('const focusableElements = focusableDialogElements(dialog)')
        expect(feedbackUi).toContain('last.focus()')
        expect(feedbackUi).toContain('first.focus()')
        expect(feedbackUi).toContain('const dialogKeyProps: WebKeyDownProps')
        expect(feedbackUi).toContain('window.setTimeout(focusDialog, delay)')
        expect(feedbackUi).toContain('document.getElementById(dialogContainerId)')
        expect(feedbackUi).toContain('dialog.focus()')
        expect(feedbackUi).toContain('nativeID={dialogContainerId}')
        expect(feedbackUi).toContain('role="dialog"')
        expect(feedbackUi).toContain('aria-modal')
        expect(feedbackUi).toContain('aria-labelledby={dialogTitleId}')
        expect(feedbackUi).toContain('aria-describedby={confirmState?.message ? dialogMessageId : undefined}')
        expect(feedbackUi).toContain('tabIndex={-1}')
        expect(feedbackUi).toContain('accessibilityViewIsModal')
        expect(feedbackUi).toContain('{...dialogKeyProps}')
        expect(feedbackUi).toContain('nativeID={dialogTitleId}')
        expect(feedbackUi).toContain('nativeID={dialogMessageId}')
    })

    it('keeps League section navigation labeled with the selected tab', () => {
        expect(leagueTabs).toContain('Draft Board')
        expect(leagueTabBar).toContain('function leagueTabBarAccessibilityLabel')
        expect(leagueTabBar).toContain('return `League sections, ${TAB_LABELS[activeTab]} selected`')
        expect(leagueTabBar).toContain('const tabBarAccessibilityLabel = leagueTabBarAccessibilityLabel(activeTab)')
        expect(leagueTabBar).toContain('const { viewportWidth, viewportHeight, compactLandscape } = useWebViewport()')
        expect(webViewportHook).toContain('const syncViewport = () => setWebViewport({ width: window.innerWidth, height: window.innerHeight })')
        expect(webViewportHook).toContain("window.addEventListener('resize', syncViewport)")
        expect(webViewportHook).toContain("return () => window.removeEventListener('resize', syncViewport)")
        expect(webViewportHook).toContain("const viewportWidth = Platform.OS === 'web' && webViewport !== null ? webViewport.width : width")
        expect(webViewportHook).toContain("const viewportHeight = Platform.OS === 'web' && webViewport !== null ? webViewport.height : height")
        expect(webViewportHook).toContain('compactLandscape: viewportWidth >= 600 && viewportHeight < 500')
        expect(leagueTabBar).toContain('const compactShortPortrait = viewportWidth < 380 && viewportHeight < 760')
        expect(leagueTabBar).toContain('const compactTabs = compactLandscape || compactShortPortrait')
        expect(leagueTabBar).toContain('compactTabs && styles.tabRowCompact')
        // Labels never abbreviate per breakpoint; the tab row scrolls instead.
        expect(leagueTabBar).toContain('{tab.label}')
        expect(leagueTabBar).not.toContain('COMPACT_TAB_LABELS')
        expect(leagueTabBar).toContain('horizontal')
        expect(leagueTabBar).toContain('showsHorizontalScrollIndicator={false}')
        expect(leagueTabBar).toContain('aria-label={tabBarAccessibilityLabel}')
        expect(leagueTabBar).toContain('aria-orientation="horizontal"')
        expect(leagueTabBar).toContain('accessibilityLabel={tabBarAccessibilityLabel}')
        expect(leagueTabBar).not.toContain('aria-label="League sections"')
        expect(leagueTabBar).not.toContain('accessibilityLabel="League sections"')
    })

    it('keeps League loading distinct from no-league empty state', () => {
        expect(leagueScreenState).toContain('loading: leagueLoading')
        expect(leagueScreenState).toContain('leagueLoading,')
        expect(leagueScreen).toContain('if (screen.leagueLoading)')
        expect(leagueScreen).toContain('message="Loading league..."')
        expect(leagueScreen).toContain('description="Fetching your teams and league settings."')
        expect(leagueScreen).toContain('icon="sync"')
        // No-league state now shows the full NoLeagueState welcome (Create/Join CTAs),
        // matching Home and Trades, instead of a bare one-line EmptyState.
        expect(leagueScreen).toContain('return <NoLeagueState />')
    })

    it('keeps the league phase rail announced as a live transition surface', () => {
        const phaseRail = leagueScreen.slice(
            leagueScreen.indexOf('function LeaguePhaseRail'),
            leagueScreen.indexOf('export default function LeagueScreen'),
        )
        expect(phaseRail).toContain('League phase: ${phase.label}, step ${activeStepPosition} of ${stepCount}. ${phase.detail}')
        expect(phaseRail).toContain('role="group"')
        expect(phaseRail).toContain('aria-label={phaseLabel}')
        expect(phaseRail).toContain('aria-live="polite"')
        expect(phaseRail).toContain('accessibilityLiveRegion="polite"')
        expect(phaseRail).toContain("aria-current={isActive ? 'step' : undefined}")
        expect(phaseRail).toContain('styles.phaseCompactSummary')
        expect(phaseRail).toContain('styles.phaseCompactLabel')
        expect(phaseRail).toContain('styles.phaseCompactDetail')
        expect(phaseRail).toContain('{phase.detail}')
        // Compact phase steps are a slim horizontal strip, not 44px tiles.
        const phaseStepCompact = leagueScreen.slice(
            leagueScreen.indexOf('phaseStepCompact: {'),
            leagueScreen.indexOf('phaseStepActive:'),
        )
        expect(phaseStepCompact).toContain('minHeight: 26')
        expect(phaseStepCompact).toContain("flexDirection: 'row'")
    })

    it('keeps compact League identity visible when the header collapses', () => {
        const leagueScreenBody = leagueScreen.slice(
            leagueScreen.indexOf('export default function LeagueScreen'),
            leagueScreen.indexOf('const styles = StyleSheet.create'),
        )
        expect(leagueScreenBody).toContain("const currentLeagueName = screen.currentLeague?.name ?? 'League'")
        expect(leagueScreenBody).toContain("const currentTeamName = screen.current.team_name ?? 'Team'")
        expect(leagueScreenBody).toContain('const compactIdentityLabel = `${currentLeagueName}, ${currentTeamName}`')
        expect(leagueScreenBody).toContain('const [webViewport, setWebViewport] = useState<{ width: number; height: number } | null>(null)')
        expect(leagueScreenBody).toContain("const viewportWidth = Platform.OS === 'web' && webViewport !== null ? webViewport.width : width")
        expect(leagueScreenBody).toContain("const viewportHeight = Platform.OS === 'web' && webViewport !== null ? webViewport.height : height")
        expect(leagueScreenBody).toContain('const syncViewport = () => setWebViewport({ width: window.innerWidth, height: window.innerHeight })')
        expect(leagueScreenBody).toContain('const compactShortPortrait = viewportWidth < 380 && viewportHeight < 760')
        expect(leagueScreenBody).toContain('const compactLeagueHeader = compactLandscape || compactShortPortrait')
        expect(leagueScreenBody).toContain('compactLeagueHeader && styles.headerCompact')
        expect(leagueScreenBody).toContain('compact={compactLeagueHeader}')
        expect(leagueScreenBody).toContain('styles.compactLeagueCrumb')
        expect(leagueScreenBody).toContain('aria-label={compactIdentityLabel}')
        expect(leagueScreenBody).toContain('accessibilityLabel={compactIdentityLabel}')
        expect(leagueScreenBody).toContain('styles.compactLeagueName')
        expect(leagueScreenBody).toContain('{currentLeagueName}')
        expect(leagueScreenBody).toContain('styles.compactLeagueDot')
        expect(leagueScreenBody).toContain('styles.compactTeamName')
        expect(leagueScreenBody).toContain('{currentTeamName}')
        expect(leagueScreen).toContain('compactLeagueName: {')
        expect(leagueScreen).toContain('compactTeamName: {')
    })

    it('keeps empty mock rooms as one actionable status', () => {
        expect(mockRoomsPanel).toContain('function MockRoomsEmptyState')
        expect(mockRoomsPanel).toContain('No mock rooms yet.')
        expect(mockRoomsPanel).toContain('Create an auction or rookie room for managers to join before starting a mock draft.')
        expect(mockRoomsPanel).toContain('Create one for managers to join before drafting.')
        expect(mockRoomsPanel).toContain('mockRoomsEmptyState')
        expect(mockRoomsPanel).toContain('mockRoomsEmptyStateCompact')
        expect(mockRoomsPanel).toContain('<MockRoomsEmptyState compact={compactComposer} />')
        expect(mockRoomsPanel).toContain('role="status"')
        expect(mockRoomsPanel).toContain('aria-live="polite"')
        expect(mockRoomsPanel).not.toContain('roomSections(true)')
        expect(mockRoomsPanel).not.toContain('No {ROOM_STATUS_LABELS[status].toLowerCase()} rooms.')
    })

    it('keeps compact populated mock room cards above the bottom nav', () => {
        expect(mockRoomsPanel).toContain('const { viewportHeight } = useWebViewport()')
        expect(mockRoomsPanel).toContain('const compactComposer = viewportHeight < 500')
        expect(mockRoomsPanel).toContain('contentContainerStyle={compactComposer ? undefined : panelStyles.panelScroll}')
        expect(mockRoomsPanel).toContain('<View style={[panelStyles.panelScroll, panelStyles.panelScrollCompactLandscape, styles.mockRoomsScrollCompact]}>')
        expect(mockRoomsPanel).toContain('mockRoomsScrollCompact: {')
        expect(mockRoomsPanel).toContain('style={[styles.roomCardTop, compact && styles.roomCardTopCompact]}')
        expect(mockRoomsPanel).toContain('{compact ? null : (')
        expect(mockRoomsPanel).toContain('{compactComposer ? null : (')
        expect(mockRoomsPanel).toContain('roomCardCompact: {')
        expect(mockRoomsPanel).toContain('minHeight: 44')
        expect(mockRoomsPanel).toContain('paddingVertical: 0')
        expect(mockRoomsPanel).toContain("justifyContent: 'center'")
        expect(mockRoomsPanel).toContain('roomCardTopCompact: { alignItems: \'center\' }')
        expect(mockRoomsPanel).toContain('aria-label={roomSectionAccessibilityLabel(status, statusRooms.length)}')
    })

    it('keeps mobile Draft Board setup controls from burying draft assets', () => {
        expect(draftSetupPanels).toContain('function draftBoardSetupMaxHeight')
        expect(draftSetupPanels).toContain('if (height < 500) return 64')
        expect(draftSetupPanels).toContain('if (width < 600) return 144')
        expect(draftSetupPanels).toContain('const boardTopMaxHeight = draftBoardSetupMaxHeight(width, height)')
        expect(draftSetupPanels).toContain("const hasActiveRookieDraft = activeDraftReady && activeDraft?.draftType === 'snake'")
        expect(draftSetupPanels).toContain("const canStartRookieDraft = activeDraftReady && currentLeagueStatus === 'offseason' && isCommissioner")
        expect(draftSetupPanels).toContain("const showRookiePrepNotice = !picksLoading && activeDraftReady && activeDraft?.draftType !== 'snake' && picks.length === 0")
        expect(draftSetupPanels).toContain('const compactRookiePrepNotice = constrainBoardTop')
        expect(draftSetupPanels).toContain('const showBoardTop = activeDraftLoading || Boolean(activeDraftError) || hasActiveRookieDraft || canStartRookieDraft || showRookiePrepNotice')
        expect(draftSetupPanels).toContain('{showBoardTop ? (')
        expect(draftSetupPanels).toContain('<View style={[styles.boardTop, styles.boardTopConstrained]}>')
        expect(draftSetupPanels).toContain('boardTopConstrained: {')
        expect(draftSetupPanels).not.toContain('const boardTopMaxHeight = height < 500 ? 64 : 188')
    })

    it('keeps draft runway phase notices as polite live statuses', () => {
        const draftPrepNotice = draftActiveState.slice(
            draftActiveState.indexOf('function DraftPrepNotice'),
            draftActiveState.indexOf('const styles = StyleSheet.create'),
        )
        expect(draftPrepNotice).toContain('role="status"')
        expect(draftPrepNotice).toContain('aria-label={accessibilityLabel}')
        expect(draftPrepNotice).toContain('aria-live="polite"')
        expect(draftPrepNotice).toContain('accessibilityLiveRegion="polite"')
        expect(draftPrepNotice).toContain('compact?: boolean')
        expect(draftPrepNotice).toContain('styles.prepNoticeCompact')
        expect(draftPrepNotice).toContain('styles.prepNoticeTitleCompact')
        expect(draftPrepNotice).toContain('styles.prepNoticeTextCompact')
        expect(draftPrepNotice).toContain('numberOfLines={compact ? 1 : undefined}')
        expect(draftSetupPanels).toContain('compact={compactSetup}')
        expect(draftSetupPanels).toContain('compact={compactRookiePrepNotice}')
        expect(draftPrepNotice).toContain("The startup auction finished before the season. Draft results live on each team's roster.")
        expect(draftPrepNotice).toContain('View Draft Board')
        expect(draftPrepNotice).toContain('Future rookie picks remain visible during the live season for trades and long-term planning.')
    })

    it('keeps active draft loading notices self-describing to assistive tech', () => {
        const loadingNotice = draftActiveState.slice(
            draftActiveState.indexOf('function activeDraftLoadingLabel'),
            draftActiveState.indexOf('function ActiveDraftEntry'),
        )
        expect(loadingNotice).toContain('Looking for an active draft room before showing draft setup controls.')
        expect(loadingNotice).toContain('const accessibilityLabel = `${label}. ${description}`')
        expect(loadingNotice).toContain('aria-label={accessibilityLabel}')
        expect(loadingNotice).toContain('accessibilityLabel={accessibilityLabel}')
        expect(loadingNotice).not.toContain('aria-label={label}')
        expect(loadingNotice).not.toContain('accessibilityLabel={label}')
    })

    it('keeps Settings waiver priority accessible as a ranked list', () => {
        expect(leagueScreen).toContain('myMemberId={screen.current?.id}')
        expect(settingsPanel).toContain('function SettingsWaiverPriorityCard')
        expect(settingsPanel).toContain('function settingsWaiverPriorityRowLabel')
        expect(settingsPanel).toContain('function settingsCompactWaiverSummaryLabel')
        expect(settingsPanel).toContain('function SettingsCompactWaiverSummary')
        expect(settingsPanel).toContain('<SettingsCompactWaiverSummary waiverOrder={waiverOrder} myMemberId={myMemberId} />')
        expect(settingsPanel).toContain('settingsCompactWaiverSummary')
        expect(settingsPanel).toContain('settingsCompactWaiverLabel')
        expect(settingsPanel).toContain('settingsCompactWaiverValue')
        expect(settingsPanel).toContain('Waiver priority ${index + 1}')
        expect(settingsPanel).toContain('role="list"')
        expect(settingsPanel).toContain('role="listitem"')
        expect(settingsPanel).toContain('your team')
        expect(settingsPanel).toContain('settingListRowMe')
        expect(settingsPanel).toContain('minHeight: 44')
        expect(settingsPanel).toContain('No waiver priorities yet.')
        expect(settingsPanel).toContain('Priority order is listed here once the season starts.')
        expect(settingsPanel).toContain('role="status"')
        expect(settingsPanel).toContain('aria-live="polite"')
        expect(settingsPanel).toContain('settingsEmptyState')
        expect(settingsPanel).toContain("const shareInviteAccessibilityLabel = inviteCode ? `Share invite code ${inviteCode}` : 'Share invite code'")
        expect(settingsPanel).toContain('aria-label={shareInviteAccessibilityLabel}')
        expect(settingsPanel).toContain('accessibilityLabel={shareInviteAccessibilityLabel}')
        expect(settingsPanel).not.toContain('if (!waiverOrder.length) return null')
        expect(settingsPanel).not.toContain('<SettingsWaiverPriorityCard waiverOrder={waiverOrder} myMemberId={myMemberId} compact />')
    })

    it('keeps standings legend copy phase-aware', () => {
        expect(leagueStandings).toContain('function standingsLegendCopy')
        expect(leagueStandings).toContain('Regular-season records stay locked while bracket play decides the champion.')
        expect(leagueStandings).toContain('Records are final for league history.')
        expect(leagueStandings).toContain('Records update as regular-season games are scored.')
    })

    it('keeps standings intro point stats aligned with visible columns', () => {
        const standingsIntro = leagueStandingsIntro.slice(
            leagueStandingsIntro.indexOf('function StandingsIntro'),
            leagueStandingsIntro.indexOf('function CompactPlayoffBracketAction'),
        )
        const standingsTableHeader = leagueStandings.slice(
            leagueStandings.indexOf('function StandingsTableHeader'),
            leagueStandings.indexOf('export function StandingsTable'),
        )
        expect(leagueStandingsIntro).toContain('function standingsTeamCountLabel')
        expect(leagueStandingsIntro).toContain("return loading ? 'Teams loading' : `${teamCount} teams`")
        expect(leagueStandingsIntro).toContain('function CompactStandingsIntro')
        expect(leagueStandingsIntro).toContain('styles.standingsCompactIntro')
        expect(leagueStandingsIntro).toContain('styles.standingsCompactStats')
        expect(leagueStandingsIntro).toContain('standingsIntroStats(status, showPa, showMaxPf, loading)')
        expect(leagueStandingsIntro).toContain('standingsTeamCountLabel(teamCount, loading)')
        expect(leagueStandingsIntro).toContain("status === 'playoffs' ? <CompactPlayoffBracketAction onOpenBracket={onOpenBracket} embedded /> : null")
        expect(leagueStandingsIntro).toContain('embedded && styles.standingsCompactActionEmbedded')
        expect(leagueStandingsIntro).not.toContain("leagueStatus === 'playoffs' ? <CompactPlayoffBracketAction onOpenBracket={onOpenBracket} /> : null")
        expect(leagueStandingsIntro).toContain('function standingsPointMetricLabels')
        expect(leagueStandingsIntro).toContain("const labels = ['PF']")
        expect(leagueStandingsIntro).toContain("if (showMaxPf) labels.push('MAX PF')")
        expect(leagueStandingsIntro).toContain("if (showPa) labels.push('PA')")
        expect(leagueStandingsIntro).toContain('function standingsPointStatLabel')
        expect(leagueStandingsIntro).toContain('if (loading) return `${metricLabel} loading`')
        expect(leagueStandingsIntro).toContain("standingsPointMetricLabels(showPa, showMaxPf).join(' / ')")
        expect(leagueStandings).toContain("standingsPointMetricLabels(showPa, showMaxPf).map((label) => pointTermLabels[label]).join(' · ')")
        expect(leagueStandingsIntro).toContain("if (loading) return ['Records loading', standingsPointStatLabel(status, showPa, showMaxPf, true)]")
        expect(leagueStandingsIntro).toContain('standingsIntroStats(status, showPa, showMaxPf, loading)')
        expect(leagueStandings).toContain('const { viewportWidth, compactLandscape } = useWebViewport()')
        expect(leagueStandings).toContain('const compactPhoneLandscape = compactLandscape && viewportWidth < 700')
        expect(leagueStandings).toContain('const narrowRows = viewportWidth < 440 || compactPhoneLandscape')
        expect(leagueStandings).toContain('const compactHeader = compactLandscape || narrowRows')
        expect(leagueStandings).toContain('contentContainerStyle={compactLandscape ? styles.standingsContentCompactLandscape : styles.standingsContent}')
        expect(leagueStandings).toContain('const standingsHeader = (')
        expect(leagueStandings).toContain('const standingsList = (')
        expect(leagueStandings).toContain('{compactLandscape ? standingsList : standingsHeader}')
        expect(leagueStandings).toContain('{compactLandscape ? standingsHeader : standingsList}')
        expect(leagueStandings).toContain('narrowRows={narrowRows}')
        expect(leagueStandings).toContain('narrow={narrowRows}')
        expect(leagueStandings).toContain('function standingsRecordLabel')
        expect(leagueStandings).toContain('standingsRowNarrow')
        expect(leagueStandings).toContain('paddingVertical: 0')
        // Narrow rows are a one-line mini-table (rank/team + W-L, PF, PA
        // columns), not per-value pill chips.
        expect(leagueStandings).toContain('standingsRecordNarrow')
        expect(leagueStandings).toContain('standingsPtsNarrow')
        expect(leagueStandings).toContain('{standingsRecordLabel(item)}')
        expect(leagueStandings).not.toContain('standingsStatNarrow')
        expect(leagueStandings).not.toContain('standingsStatLabelNarrow')
        // Playoff cutoff mirrors the server seeding convention (6 with 10+
        // teams, otherwise 4) and only renders in seed order.
        expect(leagueStandings).toContain('function playoffTeamCount')
        expect(leagueStandings).toContain('return teamCount >= 10 ? 6 : 4')
        expect(leagueStandings).toContain('function PlayoffCutLine')
        expect(leagueStandings).toContain("sortBy === 'wins' && sortDir === 'desc' && sorted.length > cutTeamCount ? cutTeamCount : -1")
        expect(leagueStandings).toContain('<PlayoffCutLine teamCount={cutTeamCount} />')
        expect(leagueStandings).toContain('Playoff line')
        expect(leagueStandingsIntro).toContain('const teamStat = standingsTeamCountLabel(teamCount, loading)')
        expect(standingsIntro).toContain('const accessibilityLabel = `${intro.title}. ${intro.copy} ${teamStat}. ${recordStat}. ${pointsStat}.`')
        expect(standingsIntro).toContain('aria-busy={loading ? true : undefined}')
        expect(standingsIntro).toContain('accessibilityState={{ busy: loading }}')
        expect(standingsTableHeader).toContain('loading?: boolean')
        expect(standingsTableHeader).toContain('loading={loading}')
        expect(leagueStandings).toContain('showPa={showPa}')
        expect(leagueStandings).toContain('showMaxPf={showMaxPf}')
    })

    it('keeps standings sort controls aligned with responsive columns', () => {
        const standingsHeader = leagueStandings.slice(
            leagueStandings.indexOf('const StandingsListHeader'),
            leagueStandings.indexOf('function playoffTeamCount'),
        )
        expect(leagueStandings).toContain('function standingsSortIsVisible')
        expect(leagueStandings).toContain("if (key === 'pa') return showPa")
        expect(leagueStandings).toContain("if (key === 'maxPf') return showMaxPf")
        expect(leagueStandings).toContain('if (standingsSortIsVisible(sortBy, showPa, showMaxPf)) return')
        expect(leagueStandings).toContain("setSortBy('pf')")
        expect(leagueStandings).toContain("setSortDir(defaultSortDirection('pf'))")
        expect(standingsHeader).toContain('standingsSortLiveStatus')
        expect(standingsHeader).toContain('role="status"')
        expect(standingsHeader).toContain('aria-label={sortControlsLabel}')
        expect(standingsHeader).toContain('role="toolbar"')
        expect(standingsHeader).toContain('aria-live="polite"')
        expect(standingsHeader).toContain('accessibilityLiveRegion="polite"')
        expect(standingsHeader).toContain('const narrowSortButton = (key: StandingsSortKey, label: string, colStyle: object)')
        expect(standingsHeader).toContain('if (narrow)')
        expect(standingsHeader).toContain('styles.standingsHeaderNarrow')
        expect(standingsHeader).toContain('styles.standingsSortCellNarrow')
        // Narrow sort buttons double as the mini-table column headers, sized
        // to the columns they sort.
        expect(standingsHeader).toContain("narrowSortButton('wins', 'W-L', styles.standingsRecordColNarrow)")
        expect(standingsHeader).toContain("narrowSortButton('pf', 'PF', styles.standingsPtsColNarrow)")
        expect(standingsHeader).toContain("showPa ? narrowSortButton('pa', 'PA', styles.standingsPtsColNarrow) : null")
    })

    it('keeps empty standings statuses self-describing to assistive tech', () => {
        expect(leagueStandingsIntro).toContain('function StandingsContextHeader')
        expect(leagueStandings).toContain('function StandingsTableHeader')
        expect(leagueStandings).toContain('teamCount={0}')
        expect(leagueStandings).toContain('loading={loading}')
        expect(leagueStandings).toContain('Loading standings. Fetching teams, records, and point totals.')
        expect(leagueStandings).toContain('No league members yet. Invite managers to fill the standings table before the draft.')
        expect(leagueStandings).toContain('role="status"')
        expect(leagueStandings).toContain('aria-label={emptyState.accessibilityLabel}')
        expect(leagueStandings).not.toContain("accessibilityLabel: 'No league members yet',")
        expect(leagueStandings).not.toContain("accessibilityLabel: 'Loading standings',")
    })

    it('keeps empty league activity statuses self-describing to assistive tech', () => {
        expect(leagueActivityFeed).toContain('Loading league activity. Fetching adds, drops, trades, and league updates.')
        expect(leagueActivityFeed).toContain('No league activity yet. Adds, drops, and trades are listed here.')
        expect(leagueActivityFeed).toContain('ListEmptyComponent={ListEmpty}')
        expect(leagueActivityFeed).not.toContain("accessibilityLabel: 'No league activity yet',")
        expect(leagueActivityFeed).not.toContain("accessibilityLabel: 'Loading league activity',")
    })

    it('keeps compact History activity rows clear of the bottom nav', () => {
        const activityFeed = leagueActivityFeed.slice(
            leagueActivityFeed.indexOf('function ActivityRow'),
            leagueActivityFeed.indexOf('const styles = StyleSheet.create'),
        )
        expect(activityFeed).toContain('compact?: boolean')
        expect(activityFeed).toContain('const avatarSize = compact ? 32 : 40')
        expect(activityFeed).toContain('compact && styles.txRowCompact')
        expect(activityFeed).toContain('compact && styles.txPlayerCompact')
        expect(activityFeed).toContain('numberOfLines={compact ? 1 : 2}')
        expect(activityFeed).toContain('const { compactLandscape } = useWebViewport()')
        expect(activityFeed).toContain('compact={compactLandscape}')
        expect(activityFeed).toContain("key={compactLandscape ? 'compact-activity' : 'activity'}")
        expect(activityFeed).toContain('extraData={compactLandscape}')
        expect(leagueActivityFeed).toContain('txRowCompact: {')
        expect(leagueActivityFeed).toContain('minHeight: 52')
        expect(leagueActivityFeed).toContain('txPlayerCompact: { fontSize: fontSize.sm }')
    })

    it('keeps draft asset filters honest while member identity loads', () => {
        expect(draftSetupPanels).toContain('currentLeagueStatus?: LeagueStatus')
        expect(draftSetupPanels).toContain('leagueStatus={currentLeagueStatus}')
        expect(leaguePicksBank).toContain('function pickLedgerIntroCopy')
        expect(leaguePicksBank).toContain('function pickLedgerCompactCopy')
        expect(leaguePicksBank).toContain("return totalCount > 0 ? 'Refreshing draft assets' : 'Draft assets loading'")
        expect(leaguePicksBank).toContain('const compactCopy = pickLedgerCompactCopy(intro, loading, totalCount)')
        expect(leaguePicksBank).toContain('const headerAccessibilityLabel = `Draft assets. ${compact ? compactCopy : intro.copy} ${totalStatLabel}. ${mineStatLabel}. ${tradedStatLabel}.`')
        expect(leaguePicksBank).toContain('Future rookie picks stay visible during the live season for trades and long-term planning.')
        expect(leaguePicksBank).toContain('Pick ownership is the source of truth before the rookie draft clock starts.')
        expect(leaguePicksBank).toContain('Startup draft is live while future rookie pick ownership remains available for roster planning and trade context.')
        expect(leaguePicksBank).toContain('Drafting with pick context')
        expect(leaguePicksBank).toContain('Live-season trade assets')
        expect(leaguePicksBank).toContain('Rookie draft ownership')
        expect(leaguePicksBank).toContain('styles.picksLedgerCompactSummary')
        expect(leaguePicksBank).toContain('{compactCopy}')
        expect(leaguePicksBank).toContain('{intro.copy}')
        expect(leaguePicksBank).toContain('aria-busy={loading ? true : undefined}')
        expect(leaguePicksBank).toContain('accessibilityState={{ busy: loading }}')
        expect(leaguePicksBank).toContain('leagueStatus?: LeagueStatus')
        expect(leaguePicksBank).toContain('leagueStatus={leagueStatus}')
        expect(leaguePicksBank).toContain('const { viewportWidth, viewportHeight, compactLandscape } = useWebViewport()')
        expect(leaguePicksBank).toContain('const narrowRows = viewportWidth < 440')
        expect(leaguePicksBank).toContain('const compactHeader = viewportHeight < 500 || narrowRows')
        expect(leaguePicksBank).toContain('const compactRows = compactHeader || narrowRows')
        expect(leaguePicksBank).toContain('const landscapeDenseRows = compactLandscape && !narrowRows')
        expect(leaguePicksBank).toContain('const deferHeaderUntilAfterRows = compactLandscape && flatData.length > 0')
        expect(leaguePicksBank).toContain('const ledgerHeader = (')
        expect(leaguePicksBank).toContain('{deferHeaderUntilAfterRows ? null : ledgerHeader}')
        expect(leaguePicksBank).toContain('{deferHeaderUntilAfterRows ? ledgerHeader : null}')
        expect(leaguePicksBank).toContain('if (!compactRows) result.push({ type: \'yearHeader\'')
        expect(leaguePicksBank).toContain('showColumns={flatData.length > 0 && !compactRows}')
        expect(leaguePicksBank).toContain('picksBankRowLandscapeDense')
        expect(leaguePicksBank).toContain('minHeight: 28')
        expect(leaguePicksBank).toContain('landscapeDense={landscapeDenseRows}')
        expect(leaguePicksBank).toContain('picksBankRowNarrow')
        expect(leaguePicksBank).toContain('paddingVertical: spacing.md')
        expect(leaguePicksBank).toContain('gap: spacing.xxs')
        expect(leaguePicksBank).toContain('picksBankRoundCompact: { width: 68 }')
        expect(leaguePicksBank).toContain("picksBankRoundNarrow: { width: 'auto' }")
        expect(leaguePicksBank).toContain('picksBankFromWrapNarrow: { marginLeft: 0 }')
        expect(leaguePicksBank).toContain("picksBankOwnerNarrow: { width: 'auto', textAlign: 'left' }")
        expect(leaguePicksBank).toContain('function effectivePickFilter')
        expect(leaguePicksBank).toContain("filter === 'mine' && !hasMemberId ? 'all' : filter")
        expect(leaguePicksBank).toContain('function pickFilterOptions')
        expect(leaguePicksBank).toContain("option.value !== 'mine'")
        expect(leaguePicksBank).toContain('function pickFilterGroupAccessibilityLabel')
        expect(leaguePicksBank).toContain('return `Draft asset filters, showing ${active}`')
        expect(leaguePicksBank).toContain('const filterAccessibilityLabel = pickFilterGroupAccessibilityLabel(filter, totalCount, mineCount, tradedCount, hasMemberId, loading)')
        expect(leaguePicksBank).toContain('accessibilityLabel={filterAccessibilityLabel}')
        expect(leaguePicksBank).toContain("if (!hasMemberId && filter === 'mine') setFilter('all')")
        expect(leaguePicksBank).toContain('Mine loading')
        expect(leaguePicksBank).toContain('loading?: boolean')
        expect(leaguePicksBank).toContain("const pickCountState = (count: number) => loading ? 'loading' : countLabel(count, 'pick')")
        expect(leaguePicksBank).toContain("const totalStatLabel = loading ? 'Assets loading' : `${totalCount} total`")
        expect(leaguePicksBank).toContain("const tradedStatLabel = loading ? 'Traded loading' : `${tradedCount} traded`")
        expect(leaguePicksBank).toContain('`Show my draft picks, ${pickCountState(mineCount)}`')
        expect(leaguePicksBank).toContain('`Show all draft picks, ${pickCountState(totalCount)}`')
        expect(leaguePicksBank).toContain('loading={loading}')
        expect(leaguePicksBank).toContain('function pickListName')
        expect(leaguePicksBank).toContain('pickListAccessibilityLabel(activeFilter, visiblePicks.length)')
        expect(leaguePicksBank).toContain('function pickListLoadingAccessibilityLabel')
        expect(leaguePicksBank).toContain('function pickListRefreshingAccessibilityLabel')
        expect(leaguePicksBank).toContain('`${pickListName(filter)} loading, ${countLabel(count, \'pick\')} currently shown`')
        expect(leaguePicksBank).toContain('hasVisiblePicks')
        expect(leaguePicksBank).toContain('pickListRefreshingAccessibilityLabel(activeFilter, visiblePicks.length)')
        expect(leaguePicksBank).toContain('pickListLoadingAccessibilityLabel(activeFilter)')
        expect(leaguePicksBank).toContain('compact={compactRows}')
        expect(leaguePicksBank).toContain('narrow={narrowRows}')
        expect(leaguePicksBank).toContain('picksBankInlineLabel')
        expect(leaguePicksBank).toContain('{compact ? <Text style={styles.picksBankInlineLabel}>From </Text> : null}')
        expect(leaguePicksBank).toContain('{compact ? <Text style={styles.picksBankInlineLabel}>Owner </Text> : null}')
        expect(leaguePicksBank).toContain('pickFilterTabId(activeFilter)')
        expect(segmentedControl).toContain('aria-orientation="horizontal"')
        expect(leaguePicksBank).not.toContain('accessibilityLabel="Draft asset filters"')
    })

    it('keeps empty draft assets self-describing to assistive tech', () => {
        expect(leaguePicksBank).toContain('<PicksLedgerHeader')
        expect(leaguePicksBank).toContain('flatHasRows={flatData.length > 0}')
        expect(leaguePicksBank).toContain('totalCount={picks.length}')
        expect(leaguePicksBank).toContain('function pickPanelAccessibilityLabel')
        expect(leaguePicksBank).toContain('if (hasVisiblePicks && loading) return `${listAccessibilityLabel}. ${empty.description}`')
        expect(leaguePicksBank).toContain('if (hasVisiblePicks) return `${listAccessibilityLabel} results`')
        expect(leaguePicksBank).toContain('return `${listAccessibilityLabel} results. ${empty.message} ${empty.description}`')
        expect(leaguePicksBank).toContain('return `${listAccessibilityLabel}. ${empty.description}`')
        expect(leaguePicksBank).not.toContain('return `Loading draft assets. ${empty.description}`')
        expect(leaguePicksBank).toContain('role="tabpanel"')
        expect(leaguePicksBank).toContain('No future draft picks to display.')
        expect(leaguePicksBank).toContain('Rookie pick assets appear here once the league creates them.')
        expect(leaguePicksBank).toContain('const panelAccessibilityLabel = pickPanelAccessibilityLabel({')
        expect(leaguePicksBank).toContain('const hasVisiblePicks = visiblePicks.length > 0')
        expect(leaguePicksBank).toContain('hasVisiblePicks,')
        expect(leaguePicksBank).toContain('aria-labelledby={pickFilterTabId(activeFilter)}')
        expect(leaguePicksBank).not.toContain("const panelAccessibilityLabel = loading && !picks.length")
        expect(leaguePicksBank).not.toContain('hasPicks: picks.length > 0')
        expect(leaguePicksBank).not.toContain("'Draft picks, 0 picks'")
        expect(leaguePicksBank).not.toContain('role={resultsRole}')
    })

    it('adds a persistent season-long lineup optimizer processor', () => {
        expect(goalMigration).toContain('CREATE TABLE IF NOT EXISTS public.lineup_optimizer_settings')
        expect(goalMigration).toContain("'nba-lineup-optimizer'")
        expect(goalMigration).toContain("public.invoke_edge_function('lineup-optimizer')")
        expect(lineupOptimizer).toContain("from('lineup_optimizer_settings')")
        expect(lineupOptimizer).toContain('auto_set_lineup_atomic')
        expect(lineupOptimizer).toContain('compareScore')
        expect(lineupOptimizer).toContain('healthy')
        expect(read('components/AutoSetModal.tsx')).toContain('Enable Season Optimizer')
        expect(read('app/(modals)/lineup.tsx')).toContain('setLineupOptimizerEnabled')
    })
})
