export const parseArgs = () => {
  const args = new Map()
  for (const arg of process.argv.slice(2)) {
    const match = arg.match(/^--([^=]+)=(.*)$/)
    if (match) args.set(match[1], match[2])
  }
  return {
    seasons: Number(args.get('seasons') ?? process.env.E2E_SEASONS ?? 10),
    keepGoing: args.get('keep-going') === 'true' || process.env.E2E_KEEP_GOING === '1',
    repeatScenariosEverySeason: args.get('repeat-scenarios-every-season') === 'true' || process.env.E2E_REPEAT_SCENARIOS_EVERY_SEASON === '1',
    fakePort: Number(args.get('fake-port') ?? process.env.FAKE_UPSTREAM_PORT ?? 4555),
    browser: args.get('browser') === 'true' || process.env.E2E_ENABLE_BROWSER === '1',
    browserFullSweep: args.get('browser-full-sweep') === 'true' || process.env.E2E_BROWSER_FULL_SWEEP === '1',
    browserAuth: args.get('browser-auth') === 'true' || process.env.E2E_ENABLE_BROWSER_AUTH === '1',
    browserPerf: args.get('browser-perf') === 'true' || process.env.E2E_ENABLE_BROWSER_PERF === '1',
    browserGameplay: args.get('browser-gameplay') === 'true' || process.env.E2E_ENABLE_BROWSER_GAMEPLAY === '1',
    browserLineup: args.get('browser-lineup') === 'true' || process.env.E2E_ENABLE_BROWSER_LINEUP === '1',
    browserLineupAutoSet: args.get('browser-lineup-auto-set') === 'true' || process.env.E2E_ENABLE_BROWSER_LINEUP_AUTO_SET === '1',
    browserLineupLocked: args.get('browser-lineup-locked') === 'true' || process.env.E2E_ENABLE_BROWSER_LINEUP_LOCKED === '1',
    browserPlayoff: args.get('browser-playoff') === 'true' || process.env.E2E_ENABLE_BROWSER_PLAYOFF === '1',
    browserRookieDraft: args.get('browser-rookie-draft') === 'true' || process.env.E2E_ENABLE_BROWSER_ROOKIE_DRAFT === '1',
    browserWaiver: args.get('browser-waiver') === 'true' || process.env.E2E_ENABLE_BROWSER_WAIVER === '1',
    browserWaiverDrop: args.get('browser-waiver-drop') === 'true' || process.env.E2E_ENABLE_BROWSER_WAIVER_DROP === '1',
    browserWaiverIrBlock: args.get('browser-waiver-ir-block') === 'true' || process.env.E2E_ENABLE_BROWSER_WAIVER_IR_BLOCK === '1',
    browserTrade: args.get('browser-trade') === 'true' || process.env.E2E_ENABLE_BROWSER_TRADE === '1',
    browserTradeAccept: args.get('browser-trade-accept') === 'true' || process.env.E2E_ENABLE_BROWSER_TRADE_ACCEPT === '1',
    browserTradeTerminal: args.get('browser-trade-terminal') === 'true' || process.env.E2E_ENABLE_BROWSER_TRADE_TERMINAL === '1',
    browserTradeFuturePick: args.get('browser-trade-future-pick') === 'true' || process.env.E2E_ENABLE_BROWSER_TRADE_FUTURE_PICK === '1',
    browserTradeFuturePickAccept: args.get('browser-trade-future-pick-accept') === 'true' || process.env.E2E_ENABLE_BROWSER_TRADE_FUTURE_PICK_ACCEPT === '1',
    browserTradeOverflowAccept: args.get('browser-trade-overflow-accept') === 'true' || process.env.E2E_ENABLE_BROWSER_TRADE_OVERFLOW_ACCEPT === '1',
    browserTradePostDeadline: args.get('browser-trade-post-deadline') === 'true' || process.env.E2E_ENABLE_BROWSER_TRADE_POST_DEADLINE === '1',
    browserTradeVeto: args.get('browser-trade-veto') === 'true' || process.env.E2E_ENABLE_BROWSER_TRADE_VETO === '1',
    browserLeagueLifecycle: args.get('browser-league-lifecycle') === 'true' || process.env.E2E_ENABLE_BROWSER_LEAGUE_LIFECYCLE === '1',
    leagueLifecycle: args.get('league-lifecycle') === 'true' || process.env.E2E_ENABLE_LEAGUE_LIFECYCLE === '1',
    pickChain: args.get('pick-chain') === 'true' || process.env.E2E_ENABLE_PICK_CHAIN === '1',
    push: args.get('push') === 'true' || process.env.E2E_ENABLE_PUSH === '1',
    draftPush: args.get('draft-push') === 'true' || process.env.E2E_ENABLE_DRAFT_PUSH === '1',
    history: args.get('history') === 'true' || process.env.E2E_ENABLE_HISTORY === '1',
    realtime: args.get('realtime') === 'true' || process.env.E2E_ENABLE_REALTIME === '1',
    midlifeMigration: args.get('midlife-migration') === 'true' || process.env.E2E_ENABLE_MIDLIFE_MIGRATION === '1',
    auction: args.get('auction') === 'true' || process.env.E2E_ENABLE_AUCTION === '1',
    playoffs: args.get('playoffs') === 'true' || process.env.E2E_ENABLE_PLAYOFFS === '1',
    tiebreakers: args.get('tiebreakers') === 'true' || process.env.E2E_ENABLE_TIEBREAKERS === '1',
    settings: args.get('settings') === 'true' || process.env.E2E_ENABLE_SETTINGS === '1',
    scoring: args.get('scoring') === 'true' || process.env.E2E_ENABLE_SCORING === '1',
    waiverProcessing: args.get('waiver-processing') === 'true' || process.env.E2E_ENABLE_WAIVER_PROCESSING === '1',
    injuryFilter: args.get('injury-filter') === 'true' || process.env.E2E_ENABLE_INJURY_FILTER === '1',
    tradeAccept: args.get('trade-accept') === 'true' || process.env.E2E_ENABLE_TRADE_ACCEPT === '1',
    tradeVeto: args.get('trade-veto') === 'true' || process.env.E2E_ENABLE_TRADE_VETO === '1',
    rookieDraft: args.get('rookie-draft') === 'true' || process.env.E2E_ENABLE_ROOKIE_DRAFT === '1',
    seasonReset: args.get('season-reset') === 'true' || process.env.E2E_ENABLE_SEASON_RESET === '1',
  }
}
