-- Seed nba_draft_number for 2025 NBA Draft picks
-- Source: 2025 NBA Draft (held June 25-26, 2025, Barclays Center, Brooklyn)
-- https://en.wikipedia.org/wiki/2025_NBA_draft

UPDATE players SET nba_draft_number = 1  WHERE display_name = 'Cooper Flagg';
UPDATE players SET nba_draft_number = 2  WHERE display_name = 'Dylan Harper';
UPDATE players SET nba_draft_number = 3  WHERE display_name = 'VJ Edgecombe' OR display_name = 'V.J. Edgecombe';
UPDATE players SET nba_draft_number = 4  WHERE display_name = 'Kon Knueppel';
UPDATE players SET nba_draft_number = 5  WHERE display_name = 'Ace Bailey';
UPDATE players SET nba_draft_number = 6  WHERE display_name = 'Tre Johnson';
UPDATE players SET nba_draft_number = 7  WHERE display_name = 'Jeremiah Fears';
UPDATE players SET nba_draft_number = 8  WHERE display_name = 'Egor Demin' OR display_name = 'Egor Dëmin';
UPDATE players SET nba_draft_number = 9  WHERE display_name = 'Collin Murray-Boyles';
UPDATE players SET nba_draft_number = 10 WHERE display_name = 'Khaman Maluach';
UPDATE players SET nba_draft_number = 11 WHERE display_name = 'Cedric Coward';
UPDATE players SET nba_draft_number = 12 WHERE display_name = 'Noa Essengue';
UPDATE players SET nba_draft_number = 13 WHERE display_name = 'Derik Queen';
UPDATE players SET nba_draft_number = 14 WHERE display_name = 'Carter Bryant';
UPDATE players SET nba_draft_number = 15 WHERE display_name = 'Thomas Sorber';
UPDATE players SET nba_draft_number = 16 WHERE display_name = 'Yang Hansen';
UPDATE players SET nba_draft_number = 17 WHERE display_name = 'Joan Beringer';
UPDATE players SET nba_draft_number = 18 WHERE display_name = 'Walter Clayton Jr.' OR display_name = 'Walter Clayton';
UPDATE players SET nba_draft_number = 19 WHERE display_name = 'Nolan Traore';
UPDATE players SET nba_draft_number = 20 WHERE display_name = 'Kasparas Jakucionis' OR display_name = 'Kasparas Jakučionis';
UPDATE players SET nba_draft_number = 21 WHERE display_name = 'Will Riley';
UPDATE players SET nba_draft_number = 22 WHERE display_name = 'Drake Powell';
UPDATE players SET nba_draft_number = 23 WHERE display_name = 'Asa Newell';
UPDATE players SET nba_draft_number = 24 WHERE display_name = 'Nique Clifford';
UPDATE players SET nba_draft_number = 25 WHERE display_name = 'Jase Richardson';
UPDATE players SET nba_draft_number = 26 WHERE display_name = 'Ben Saraf';
UPDATE players SET nba_draft_number = 27 WHERE display_name = 'Danny Wolf';
UPDATE players SET nba_draft_number = 28 WHERE display_name = 'Hugo Gonzalez' OR display_name = 'Hugo González';
UPDATE players SET nba_draft_number = 29 WHERE display_name = 'Liam McNeeley';
UPDATE players SET nba_draft_number = 30 WHERE display_name = 'Yanic Konan Niederhauser' OR display_name = 'Yanic Niederhauser' OR display_name = 'Yanic Konan Niederhäuser';
UPDATE players SET nba_draft_number = 31 WHERE display_name = 'Rasheer Fleming';
UPDATE players SET nba_draft_number = 32 WHERE display_name = 'Noah Penda';
UPDATE players SET nba_draft_number = 33 WHERE display_name = 'Sion James';
UPDATE players SET nba_draft_number = 34 WHERE display_name = 'Ryan Kalkbrenner';
UPDATE players SET nba_draft_number = 35 WHERE display_name = 'Johni Broome';
UPDATE players SET nba_draft_number = 36 WHERE display_name = 'Adou Thiero';
UPDATE players SET nba_draft_number = 37 WHERE display_name = 'Chaz Lanier';
UPDATE players SET nba_draft_number = 38 WHERE display_name = 'Kam Jones';
UPDATE players SET nba_draft_number = 39 WHERE display_name = 'Alijah Martin';
UPDATE players SET nba_draft_number = 40 WHERE display_name = 'Micah Peavy';
UPDATE players SET nba_draft_number = 41 WHERE display_name = 'Koby Brea';
UPDATE players SET nba_draft_number = 42 WHERE display_name = 'Maxime Raynaud';
UPDATE players SET nba_draft_number = 43 WHERE display_name = 'Jamir Watkins';
UPDATE players SET nba_draft_number = 44 WHERE display_name = 'Brooks Barnhizer';
UPDATE players SET nba_draft_number = 45 WHERE display_name = 'Rocco Zikarsky';
UPDATE players SET nba_draft_number = 46 WHERE display_name = 'Amari Williams';
UPDATE players SET nba_draft_number = 47 WHERE display_name = 'Bogoljub Markovic';
UPDATE players SET nba_draft_number = 48 WHERE display_name = 'Javon Small';
UPDATE players SET nba_draft_number = 49 WHERE display_name = 'Tyrese Proctor';
UPDATE players SET nba_draft_number = 50 WHERE display_name = 'Kobe Sanders';
UPDATE players SET nba_draft_number = 51 WHERE display_name = 'Mohamed Diawara';
UPDATE players SET nba_draft_number = 52 WHERE display_name = 'Alex Toohey';
UPDATE players SET nba_draft_number = 53 WHERE display_name = 'John Tonje';
UPDATE players SET nba_draft_number = 54 WHERE display_name = 'Taelon Peter';
UPDATE players SET nba_draft_number = 55 WHERE display_name = 'Lachlan Olbrich';
UPDATE players SET nba_draft_number = 56 WHERE display_name = 'Will Richard';
UPDATE players SET nba_draft_number = 57 WHERE display_name = 'Max Shulga';
UPDATE players SET nba_draft_number = 58 WHERE display_name = 'Saliou Niang';
UPDATE players SET nba_draft_number = 59 WHERE display_name = 'Jahmai Mashack';
