import { StyleSheet } from 'react-native'
import { colors, fontSize, fontWeight, layout, radii, spacing, textStyles } from '@/constants/tokens'

export const styles = StyleSheet.create({
    // Screens add the page's side padding from usePageMetrics().
    scroll: {
        paddingTop: spacing.xl,
        paddingBottom: spacing['6xl'],
        gap: spacing.sm,
        width: '100%',
        maxWidth: layout.formMaxWidth + 2 * layout.pagePadX.regular,
        alignSelf: 'center',
    },
    scrollCompact: { paddingTop: spacing.md, gap: spacing.sm, paddingBottom: spacing['5xl'] },

    headerSave: {
        minHeight: 44,
        paddingHorizontal: spacing.lg,
        borderRadius: radii.md,
        borderCurve: 'continuous' as const,
        backgroundColor: colors.primary,
        alignItems: 'center',
        justifyContent: 'center',
    },
    headerSaveDisabled: { opacity: 0.5 },
    headerSaveText: { color: colors.textWhite, fontWeight: fontWeight.bold, fontSize: fontSize.md },

    lifecycleCard: {
        backgroundColor: colors.bgCard,
        borderRadius: radii.lg,
        borderCurve: 'continuous' as const,
        borderWidth: 1,
        borderColor: colors.borderLight,
        padding: spacing.xl,
        gap: spacing.lg,
    },
    lifecycleCardCompact: {
        padding: spacing.md,
        gap: spacing.md,
    },
    lifecycleCopy: {
        gap: spacing.xs,
    },
    lifecycleTitle: {
        fontSize: fontSize.lg,
        fontWeight: fontWeight.bold,
        color: colors.textPrimary,
    },
    lifecycleDetail: { ...textStyles.meta },
    lifecycleActions: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        alignItems: 'flex-start',
        gap: spacing.md,
    },
    lifecycleActionsCompact: {
        gap: spacing.sm,
    },

    sectionTitle: {
        ...textStyles.sectionLabel,
        marginTop: spacing.lg,
        marginLeft: spacing.xs,
    },

    card: {
        backgroundColor: colors.bgCard,
        borderRadius: radii.lg,
        borderCurve: 'continuous' as const,
        borderWidth: 1,
        borderColor: colors.borderLight,
        overflow: 'hidden',
    },
    row: { minHeight: 48, flexDirection: 'row', alignItems: 'center', gap: spacing.md, paddingHorizontal: spacing.lg, paddingVertical: spacing.xs },
    rowStacked: { flexDirection: 'column', alignItems: 'stretch', gap: spacing.sm },
    rowBorder: { borderBottomWidth: 1, borderBottomColor: colors.separator },
    rowLabel: { flex: 1, fontSize: fontSize.md, color: colors.textPrimary },
    settingHint: {
        ...textStyles.meta,
        paddingHorizontal: spacing.lg,
        paddingVertical: spacing.sm,
        borderBottomWidth: 1,
        borderBottomColor: colors.separator,
    },

    // 16px keeps iOS Safari from zooming the page when a field is focused.
    scoreInput: {
        width: 72,
        minHeight: 40,
        textAlign: 'right',
        fontSize: fontSize.lg,
        fontWeight: fontWeight.semibold,
        color: colors.primaryDark,
        padding: 0,
    },
    segmentRow: {
        flexDirection: 'row',
        gap: spacing.sm,
    },
    segmentRowCompact: { width: '100%' },
    segmentButton: {
        minWidth: 76,
        minHeight: 44,
        alignItems: 'center',
        justifyContent: 'center',
        borderWidth: 1,
        borderColor: colors.borderLight,
        borderRadius: radii.md,
        borderCurve: 'continuous' as const,
        paddingHorizontal: spacing.md,
        backgroundColor: colors.bgMuted,
    },
    segmentButtonCompact: { flex: 1, minWidth: 0, paddingHorizontal: spacing.xs },
    segmentButtonActive: {
        borderColor: colors.primary,
        backgroundColor: colors.primary,
    },
    segmentButtonText: { fontSize: fontSize.sm, fontWeight: fontWeight.bold, color: colors.textSecondary },
    segmentButtonTextActive: { color: colors.textWhite },
    memberChipRow: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        gap: spacing.sm,
        padding: spacing.lg,
        paddingBottom: spacing.sm,
    },
    memberChip: {
        minHeight: 44,
        justifyContent: 'center',
        borderRadius: radii.md,
        borderCurve: 'continuous' as const,
        backgroundColor: colors.bgMuted,
        paddingHorizontal: spacing.md,
    },
    memberChipActive: { backgroundColor: colors.primary },
    memberChipText: { fontSize: fontSize.sm, fontWeight: fontWeight.bold, color: colors.textSecondary },
    memberChipTextActive: { color: colors.textWhite },
    overrideRow: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: spacing.md,
        paddingHorizontal: spacing.lg,
        paddingVertical: spacing.sm,
    },
    overrideInput: {
        flex: 1,
        minHeight: 44,
        borderWidth: 1,
        borderColor: colors.borderLight,
        borderRadius: radii.md,
        borderCurve: 'continuous' as const,
        paddingHorizontal: spacing.md,
        fontSize: fontSize.lg,
        color: colors.textPrimary,
    },
    overrideButton: {
        minWidth: 92,
        minHeight: 44,
        alignItems: 'center',
        justifyContent: 'center',
        borderRadius: radii.md,
        borderCurve: 'continuous' as const,
        backgroundColor: colors.primary,
        paddingHorizontal: spacing.md,
    },
    overrideButtonText: { fontSize: fontSize.sm, fontWeight: fontWeight.bold, color: colors.textWhite },

    stepper: { flexDirection: 'row', alignItems: 'center', gap: spacing.lg },
    stepBtn: {
        width: 44,
        height: 44,
        borderRadius: radii.md,
        borderCurve: 'continuous' as const,
        backgroundColor: colors.bgMuted,
        justifyContent: 'center',
        alignItems: 'center',
    },
    stepBtnText: { fontSize: fontSize.xl, color: colors.textPrimary, lineHeight: 24 },
    stepValue: {
        fontSize: fontSize.lg,
        fontWeight: fontWeight.bold,
        color: colors.textPrimary,
        minWidth: 20,
        textAlign: 'center',
    },

    actionButton: {
        backgroundColor: colors.bgCard,
        borderRadius: radii.md,
        borderCurve: 'continuous' as const,
        borderWidth: 1,
        borderColor: colors.primary,
        minHeight: 44,
        justifyContent: 'center',
        alignItems: 'center',
        paddingHorizontal: spacing.lg,
    },
    actionButtonGrid: {
        flexGrow: 1,
        flexBasis: 184,
    },
    actionButtonText: { color: colors.primaryDark, fontWeight: fontWeight.bold, fontSize: fontSize.md },
    actionWrap: { gap: spacing.xs },
    actionDescription: { ...textStyles.meta, paddingHorizontal: spacing.xs },
})
