import { StyleSheet } from 'react-native'
import { colors, fontSize, fontWeight, radii, spacing } from '@/constants/tokens'

export const styles = StyleSheet.create({
    container: { flex: 1, backgroundColor: colors.bgSubtle },
    scroll: { padding: spacing['2xl'], gap: spacing.md, paddingBottom: 96, width: '100%', maxWidth: 760, alignSelf: 'center' },
    scrollCompact: { paddingHorizontal: spacing.md, paddingTop: spacing.md, gap: spacing.sm, paddingBottom: spacing['5xl'] },

    screenHeader: {
        minHeight: 56,
        flexDirection: 'row',
        alignItems: 'center',
        gap: spacing.md,
        paddingHorizontal: spacing.md,
        borderBottomWidth: 1,
        borderBottomColor: colors.borderLight,
        backgroundColor: colors.bgCard,
    },
    headerBack: {
        width: 44,
        height: 44,
        alignItems: 'center',
        justifyContent: 'center',
        borderRadius: radii.md,
        borderCurve: 'continuous' as const,
        backgroundColor: colors.bgMuted,
    },
    screenTitle: {
        flex: 1,
        color: colors.textPrimary,
        fontSize: fontSize.lg,
        fontWeight: fontWeight.extrabold,
    },

    lifecycleCard: {
        backgroundColor: colors.bgScreen,
        borderRadius: radii.md,
        borderCurve: 'continuous' as const,
        borderWidth: 1,
        borderColor: colors.borderLight,
        padding: spacing.xl,
        gap: spacing.lg,
    },
    lifecycleCardCompact: {
        padding: spacing.md,
        gap: spacing.md,
    },
    lifecycleCopy: {
        gap: spacing.xs,
    },
    lifecycleTitle: {
        fontSize: fontSize.lg,
        fontWeight: fontWeight.extrabold,
        color: colors.textPrimary,
    },
    lifecycleDetail: {
        fontSize: fontSize.sm,
        lineHeight: 18,
        color: colors.textSecondary,
    },
    lifecycleActions: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        gap: spacing.md,
    },
    lifecycleActionsCompact: {
        gap: spacing.sm,
    },

    sectionTitle: {
        fontSize: fontSize.xs,
        fontWeight: fontWeight.bold,
        color: colors.textPlaceholder,
        letterSpacing: 0,
        marginTop: spacing.lg,
        marginBottom: spacing.xs,
        marginLeft: spacing.xs,
    },

    card: {
        backgroundColor: colors.bgScreen,
        borderRadius: radii.md,
        borderCurve: 'continuous' as const,
        borderWidth: 1,
        borderColor: colors.borderLight,
        overflow: 'hidden',
    },
    row: { minHeight: 44, flexDirection: 'row', alignItems: 'center', paddingHorizontal: spacing.xl, paddingVertical: spacing.lg },
    rowStacked: { flexDirection: 'column', alignItems: 'stretch', gap: spacing.sm },
    rowBorder: { borderBottomWidth: 1, borderBottomColor: colors.separator },
    rowLabel: { flex: 1, fontSize: 15, color: colors.textPrimary },
    settingHint: {
        paddingHorizontal: spacing.xl,
        paddingVertical: spacing.md,
        borderBottomWidth: 1,
        borderBottomColor: colors.separator,
        fontSize: fontSize.sm,
        lineHeight: 18,
        color: colors.textMuted,
    },

    scoreInput: {
        width: 72,
        minHeight: 44,
        textAlign: 'right',
        fontSize: 15,
        fontWeight: fontWeight.semibold,
        color: colors.primaryDark,
        padding: 0,
    },
    segmentRow: {
        flexDirection: 'row',
        gap: spacing.sm,
    },
    segmentRowCompact: { width: '100%' },
    segmentButton: {
        minWidth: 76,
        minHeight: 44,
        alignItems: 'center',
        justifyContent: 'center',
        borderWidth: 1,
        borderColor: colors.borderLight,
        borderRadius: radii.md,
        borderCurve: 'continuous' as const,
        paddingHorizontal: spacing.md,
        backgroundColor: colors.bgMuted,
    },
    segmentButtonCompact: { flex: 1, minWidth: 0, paddingHorizontal: spacing.xs },
    segmentButtonActive: {
        borderColor: colors.primary,
        backgroundColor: colors.primary,
    },
    segmentButtonText: { fontSize: fontSize.sm, fontWeight: fontWeight.bold, color: colors.textSecondary },
    segmentButtonTextActive: { color: colors.textWhite },
    memberChipRow: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        gap: spacing.sm,
        padding: spacing.lg,
        paddingBottom: spacing.sm,
    },
    memberChip: {
        minHeight: 44,
        justifyContent: 'center',
        borderRadius: radii.md,
        borderCurve: 'continuous' as const,
        backgroundColor: colors.bgMuted,
        paddingHorizontal: spacing.md,
    },
    memberChipActive: { backgroundColor: colors.primary },
    memberChipText: { fontSize: fontSize.sm, fontWeight: fontWeight.bold, color: colors.textSecondary },
    memberChipTextActive: { color: colors.textWhite },
    overrideRow: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: spacing.md,
        paddingHorizontal: spacing.lg,
        paddingVertical: spacing.sm,
    },
    overrideInput: {
        flex: 1,
        minHeight: 44,
        borderWidth: 1,
        borderColor: colors.borderLight,
        borderRadius: radii.md,
        borderCurve: 'continuous' as const,
        paddingHorizontal: spacing.md,
        fontSize: fontSize.md,
        color: colors.textPrimary,
    },
    overrideButton: {
        minWidth: 92,
        minHeight: 44,
        alignItems: 'center',
        justifyContent: 'center',
        borderRadius: radii.md,
        borderCurve: 'continuous' as const,
        backgroundColor: colors.primary,
        paddingHorizontal: spacing.md,
    },
    overrideButtonText: { fontSize: fontSize.sm, fontWeight: fontWeight.bold, color: colors.textWhite },

    stepper: { flexDirection: 'row', alignItems: 'center', gap: spacing.lg },
    stepBtn: {
        width: 44,
        height: 44,
        borderRadius: radii.md,
        borderCurve: 'continuous' as const,
        backgroundColor: colors.bgMuted,
        justifyContent: 'center',
        alignItems: 'center',
    },
    stepBtnText: { fontSize: 20, color: colors.textPrimary, lineHeight: 24 },
    stepValue: {
        fontSize: fontSize.lg,
        fontWeight: fontWeight.bold,
        color: colors.textPrimary,
        minWidth: 20,
        textAlign: 'center',
    },

    saveButton: {
        marginTop: spacing.xl,
        backgroundColor: colors.primary,
        borderRadius: radii.md,
        borderCurve: 'continuous' as const,
        height: 52,
        justifyContent: 'center',
        alignItems: 'center',
    },
    saveButtonText: { color: colors.textWhite, fontWeight: fontWeight.bold, fontSize: fontSize.lg },

    actionButton: {
        backgroundColor: colors.bgScreen,
        borderRadius: radii.md,
        borderCurve: 'continuous' as const,
        borderWidth: 1.5,
        borderColor: colors.primary,
        minHeight: 44,
        height: 52,
        justifyContent: 'center',
        alignItems: 'center',
        paddingHorizontal: spacing.lg,
    },
    actionButtonGrid: {
        flexGrow: 1,
        flexBasis: 184,
    },
    actionButtonText: { color: colors.primaryDark, fontWeight: fontWeight.bold, fontSize: fontSize.lg },
    actionWrap: { gap: spacing.xs },
    actionDescription: {
        fontSize: fontSize.xs,
        lineHeight: 16,
        color: colors.textMuted,
        paddingHorizontal: spacing.xs,
    },
})
